server:
  port: 8084

spring:
  application:
    name: goods-web
  thymeleaf:
    cache:false
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /leyou
    username: leyou
    password: leyou

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    eureka-connection-idle-timeout-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
