server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10

zuul:
  prefix: /api
  #route路由
  routes:
    item-service: /item/** #添加商品微服务的路由、伟服务都要通过网管来进行访问
    user-service: /user/** #用户微服务
    search-service: /search/** #将它交给网关，这是search服务的controller需要的
ribbon:
  connectionTimeout: 50000 #获取连接超时时间
  readTimeout: 50000 #通讯超时时间